config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/experience', to: 'pages#experience'
  get '/certification', to: 'pages#certification'
  get '/skills', to: 'pages#skills'
  # get '/interests', to: 'pages#experience'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


   def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action only: [ :home, :about, :contact]

  def about
  end

  def contact
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>
<!-- <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <link href="https://fonts.googleapis.com/css2?family=Bad+Script&family=Poiret+One&family=Special+Elite&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bad+Script&family=Poiret+One&family=Raleway:wght@200;400;500;600;700;800;900&family=Special+Elite&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Dosis:wght@500&family=Notable&family=Raleway:wght@100&display=swap" rel="stylesheet">
     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="<%= params[:controller] %>-<%= params[:action] %>">
        <%= render 'shared/navbar' %>

    <%= yield %>

  </body>

</html>

app/views/pages/about.html.erb
<section id="about-me">
          <div class="container">
           <h1 class="about-title">About Me</h1>
            <div class="row">
              <div class="col-sm-4 col-md-5">
                <div class="avatar-large">
                  <%= image_tag "frankie2 2.jpg", class:'image1' %>
                </div>
              </div>
                <div class="col-sm-7 col-md-7" id="about-paragraph-box">
                  <p class="about-paragraph">Graduated with a Bachelor degree in Cultural Heritage and a degree in Fullstack Development</p>
                  <p class="about-paragraph">Background in product and project management, mainly in the Art-Industry (2013/2017).</p>
                  <p class="about-paragraph">After more than amazing entrepreneurial experiences in the creative industry, I am keen to join a fully tech company as a Product Manager or Owner.</p>
                  <p class="about-paragraph">Thats why during Corona, I decided to add more to my technical knowledge and learn more about the technical possibilities</p>
                  <p class="about-paragraph">So, I've completed <a href="https://www.lewagon.com/" class="about-link">Le Wagon</a> coding bootcamp (Amsterdam, Batch #449 - july 2020) to add technical skills to my creative profile (HTML, CSS, Javascript, RubyOnRails).</p>
                  <p class="about-paragraph">Currently working as freelance Project Manager and Front-End Developer, And I am looking for a new challenge!</p>
                  <a href="contact.html" class="btn btn-outline-custom4" role="button">LET'S TALK</a>
                </div>
            </div>

<div class="pages-link">
<%= link_to "Let's Talk", contact_path %>
<%= link_to "Home page", root_path %>

  </div>

app/views/pages/certification.html.erb
<div class="pages-link">
<%= link_to "Let's Talk", contact_path %>
<%= link_to "Home page", root_path %>

  </div>

app/views/pages/contact.html.erb
<h1>Contact details!</h1>


<div class="pages-link">
  <%= link_to "Get to know me", about_path %>
<%= link_to "Home page", root_path %>
  </div>

app/views/pages/experience.html.erb
<div class="container">

  <div class="cards-experiences">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    Discover Rembrandt
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/lunch.jpg)">
    Kunst Rai
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/dinner.jpg)">
    Christie's @ Zuiveringshal
  </div>
</div>
  <div class="card-container">
  <div class=cards-experiences>

    <div class="card-exp-1">
      <p>discover rembrandt</p>
    </div>
    <div class="card-exp-2">
      <p>Kunst Rai</p>
    </div>  <div class="card-exp-3">
      <p>Christie's @ Westergas</p>
    </div>  <div class="card-exp-4">
      <p>Bankgiro Loterij</p>
    </div>  <div class="card-exp-5">
      <p>Studio Drift </p>
    </div>
  </div>
</div>
</div>

<div class="pages-link">

<%= link_to "Let's Talk", contact_path %>
<%= link_to "Home page", root_path %>

  </div>

app/views/pages/home.html.erb
<!-- <div class="container">
 -->
 <body>

      <div class="banner">
        <div class="container">
          <h1 class="banner-title-1">Frankie Merckelbach</h1>
            <h3 class="banner-title-2">Digital product agent who focuses on strategy, design and creative solutions.</h3>

          <a class="btn btn-outline-custom1" href="#section-0"> View More </a>
          <a class="btn btn-outline-custom2" href="mailto:frankiemerckelbach@gmail.com"> Let's Talk</a>
        </div>
      </div>
<!--  <div class="col-sm-6  col-lg-12">
 -->
        <section id="intro">
          <a id="section-0"></a>
           <div class="container">
            <div class="cards">
              <div class="acard">
                <div class="img" style='padding-bottom: 10px'>
                <%= image_tag "creativity.png" %></div>

                <h4 class="text-banner">Creativity</h4>
              </div>
              <div class="acard">
                <div class="img">
                <%= image_tag "product.png" %>
                </div>
                  <h4 class="text-banner">Operational & Product Manager</h4><h4>
              </h4></div>
              <div class="acard">
                <div class="img" style='padding-bottom: 32px'>
                <%= image_tag "webdevelopment.png" %>
                </div>
                <h4 class="text-banner">Webdesign & Development</h4>
                <h4></h4></div>
            </div>
           </div>
        </section>
        <hr align="center" width="80%" color="#fafafa" size="0.5">
        <a id="section-0"></a>

        <section id="about-me">
          <div class="container">
           <h1 class="about-title">About Me</h1>
            <div class="row">
              <div class="col-sm-4 col-md-5">
                <div class="avatar-large">
                  <%= image_tag "frankie2 2.jpg", class:'image1' %>
                </div>
              </div>
                <div class="col-sm-7 col-md-7" id="about-paragraph-box">
                  <p class="about-paragraph">Graduated with a Bachelor degree in Cultural Heritage and a degree in Fullstack Development</p>
                  <p class="about-paragraph">Background in product and project management, mainly in the Art-Industry (2013/2017).</p>
                  <p class="about-paragraph">After more than amazing entrepreneurial experiences in the creative industry, I am keen to join a fully tech company as a Product Manager or Owner.</p>
                  <p class="about-paragraph">Thats why during Corona, I decided to add more to my technical knowledge and learn more about the technical possibilities</p>
                  <p class="about-paragraph">So, I've completed <a href="https://www.lewagon.com/" class="about-link">Le Wagon</a> coding bootcamp (Amsterdam, Batch #449 - july 2020) to add technical skills to my creative profile (HTML, CSS, Javascript, RubyOnRails).</p>
                  <p class="about-paragraph">Currently working as freelance Project Manager and Front-End Developer, And I am looking for a new challenge!</p>
                  <a href="contact.html" class="btn btn-outline-custom4" role="button">LET'S TALK</a>
                </div>
            </div>
              <div class="pages-link">
              <%= link_to "Get to know me", about_path %>
              <%= link_to "Let's Talk", contact_path %>
            </div>
          </div>

        </section>

  </body>
<%= render 'shared/footer' %>

<!-- </div>
 -->

app/views/pages/index.html.erb
<!-- <div class="container">
 -->
 <body>


  <div class="responsive-nav">
    <div class="logo">
      <%= image_tag "logo5.png" %>
     </div>
   <div class="menu">
     <h4>menu</h4>
   </div>
 </div>
    <nav class="white">
        <div class="logo">
      <%= image_tag "logo5.png" %>
        </div>
        <ul>
            <li><a href="#section-1">Experiences</a></li>
            <li><a href="#section-3">Certifications</a></li>
            <li><a href="#section-2">Skills</a></li>
            <li><a href="#section-4">Interest</a></li>
           <li><a href="contact.html" class="contact">Contact</a></li>
        </ul>
      </nav>

      <div class="banner">
        <div class="container">
          <h1 class="banner-title-1">Frankie Merckelbach</h1>
            <h3 class="banner-title-2">Product Manager</h3>

          <a class="btn btn-outline-custom1" href="#section-0"> View More </a>
          <a class="btn btn-outline-custom2" href="mailto:frankiemerckelbach@gmail.com"> Let's Talk</a>
        </div>
      </div>

        <section id="intro">
          <a id="section-0"></a>
           <div class="container">
            <div class="cards">
              <div class="acard">
                <img src="#" alt="">
                <h4> Creative Mindset</h4>
              </div>
              <div class="acard">
                <img src="#" alt="">
                  <h4>Operational and Product Manager</h4><h4>
              </h4></div>
              <div class="acard">
                <img src="#" alt="">
                <h4>Development & Arts</h4><h4>
              </h4></div>
            </div>
           </div>
        </section>
        <hr align="center" width="80%" color="#fafafa" size="0.5">
        <a id="section-0"></a>

        <section id="about-me">
          <div class="container">
           <h1 class="about-title">About Me</h1>
            <div class="row">
              <div class="col-sm-5 col-md-5">
                <div class="avatar-large">
                  <%= image_tag "frankie2 2.jpg", class:'image1' %>
                </div>
              </div>
                <div class="col-sm-7 col-md-7" id="about-paragraph-box">
                  <p class="about-paragraph">Graduated with a Bachelor degree in Cultural Heritage and a degree in Fullstack Development</p>
                  <p class="about-paragraph">Background in product and project management, mainly in the Art-Industry (2013/2017).</p>
                  <p class="about-paragraph">After more than amazing entrepreneurial experiences in the creative industry, I am keen to join a fully tech company as a Product Manager or Owner.</p>
                  <p class="about-paragraph">Thats why during Corona, I decided to add more to my technical knowledge and learn more about the technical possibilities</p>
                  <p class="about-paragraph">So, I've completed <a href="https://www.lewagon.com/" class="about-link">Le Wagon</a> coding bootcamp (Amsterdam, Batch #449 - july 2020) to add technical skills to my creative profile (HTML, CSS, Javascript, RubyOnRails).</p>
                  <p class="about-paragraph">Currently working as freelance Project Manager and Front-End Developer, And I am looking for a new challenge!</p>
                  <a href="contact.html" class="btn btn-outline-custom4" role="button">LET'S TALK</a>
                </div>
            </div>
          </div>
        </section>
  <%= link_to "Get to know me", about_path %>
  <%= link_to "Let's Talk", contact_path %>

</body>
<!-- </div>
 -->

app/views/pages/skills.html.erb
<div class="pages-link">
<%= link_to "Let's Talk", contact_path %>
<%= link_to "Home page", root_path %>

  </div>

app/views/shared/_footer.html.erb
<div class="footer">
   <div class="footer-center">
    <div>
      <i class="fa fa-map-marker">
      </i>
      <p>
        Amsterdam, The Netherlands
      </p>
    </div>
    <div>
      <i class="fa fa-phone">
      </i>
      <p>+31(0)613684499</p>
    </div>
    <div>
      <i class="fa fa-envelope">
      </i>
      <p>
        <a href="mailto:frankiemerckelbach@gmail.com">frankiemerckelbach@gmail.com</a>
      </p>
    </div>
    <div class="footer-links">
    <a href="https://github.com/Frankie-Merckelbach"><i class="fab fa-github"></i>helloo</a>
    <a href="https://www.instagram.com/frankie_merckelbach/"><i class="fab fa-instagram">Hello</i></a>
    <a href="https://www.facebook.com/frankie.merckelbach"><i class="fab fa-facebook"></i>Hello</a>
    <a href="https://www.linkedin.com/in/frankie-merckelbach-51919a58/"><i class="fab fa-linkedin"></i>Hello</a>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav id="navbar" class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-nav">
    <div class="responsive-nav">
      <div class="logo">
        <%= image_tag "frankie-logo2.png" %>
       </div>
     <div class="menu">
       <h4>menu</h4>
     </div>
    </div>

    <nav class="white">
        <div class="logo">
        <%= image_tag "frankie-logo2.png" %>
        </div>
        <ul>
            <li><%= link_to 'Expierciences', experience_path %></li>
            <li><%= link_to 'Certifications', certification_path %></li>
            <li><%= link_to 'Skills', skills_path %></li>
            <li><%= link_to 'Expierciences', experience_path %></li>
<!--

            <li><a href="#section-3">Certifications</a></li>
            <li><a href="#section-2">Skills</a></li>
            <li><a href="#section-4">Interest</a></li> -->
           <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </nav>

  </div>
</nav>